### ISSUE TITLE
black screen after screensaver kicks when playing music.

### ISSUE THREAD

**Issue by davilla** [davilla/mrmc#1]
1st quirk. play music, wait for screen to go black and wiggle mouse, it wakes up but music listing is not shown.

**Comment by amet** [comment]
viz is out and we get kicked into "full screen". OSD disappears and when you wiggle mouse OSD should come back... listing is never showing anyway, its always going into OSD and viz

**Comment by amet** [comment]
try now that Viz is out completely

**Comment by davilla** [comment]
fixed
